name: inside_chassidus
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.0+12

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  json_annotation: ^3.0.1
  expandable: ^3.0.0
  cached_network_image: ^2.0.0-rc.1
  rxdart: ^0.24.0
  bloc_pattern: ^2.4.4
  path_provider: ^1.4.0
  hive: ^1.4.1
  hive_flutter: ^0.3.0+1
  font_awesome_flutter: ^8.5.0
  audio_service: ^0.10.0
  firebase_core: ^0.4.4+2
  firebase_analytics: ^5.0.11
  firebase_crashlytics: ^0.1.3
  dart_extensions: ^1.0.1
  just_audio_service:
    git:
      url: https://github.com/yringler/just_audio_service.git
      ref: 21174408109aca84cdc03c632312d585a0aa0392
    #path: ../just_audio_service

dependency_overrides:
    hive:
      git:
        url: https://github.com/hivedb/hive
        path: hive
        ref: d7ee72537a3b7ce1284bcbf5ee5f86e617a4f6fc
    hive_generator:
      git:
        url: https://github.com/hivedb/hive
        path: hive_generator
        ref: d7ee72537a3b7ce1284bcbf5ee5f86e617a4f6fc
    hive_flutter:
      git:
        url: https://github.com/hivedb/hive
        path: hive_flutter
        ref: d7ee72537a3b7ce1284bcbf5ee5f86e617a4f6fc

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^3.2.5
  hive_generator: ^0.7.0


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/