name: inside_data
description: Manage data for Inside Chassidus
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter_wordpress:
    git:
      #url: https://github.com/dreamsoftin/flutter_wordpress
      url: https://github.com/yringler/flutter_wordpress/
      ref: limit_fields
  json_annotation: ^4.4.0
  http: ^0.13.3
  html: ^0.15.0
  html_unescape: ^2.0.0
  rxdart: ^0.27.3
  drift: ^1.1.0
  sqlite3_flutter_libs: ^0.5.2
dev_dependencies: 
  build_runner: ^2.1.0
  json_serializable: ^6.1.3
  drift_dev: ^1.0.0
